### ISSUE TITLE
release before upgrading eeafaceted

### ISSUE THREAD

**Issue by sgeulette** [collective/collective.contact.contactlist#7]
Hi Thomas,

I would like to upgrade contactlist to eeafaceted >= 10.
I propose to do a release of last commits and a branch for eeafaceted < 10.
Could you add me (sgeulette) to the pypi maintainers ?

Thanks in advance

**Comment by sgeulette** [comment]
@tdesvenain Reminder for my issue...

**Comment by gbastien** [comment]
Hi @tdesvenain @vincentfretin @ebrehault 

we really need to go further with this, is it possible to add us (@sgeulette and @gbastien) as mainteners for this package on pypi?

Thank you!

Gauthier

**Comment by vincentfretin** [comment]
It seems only @tdesvenain is owner.

**Comment by gbastien** [comment]
Hi @tdesvenain 

ping ;-)

Gauthier

**Comment by tdesvenain** [comment]
Hi @gbastien @sgeulette i added sgeulette, what is your pypi login gbastien ?

**Comment by tdesvenain** [comment]
Hi sorry for the delay i loose the notification

**Comment by gbastien** [comment]
Hi @tdesvenain

It is gauthierbastien, thanks !

**Comment by sgeulette** [comment]
Hi @tdesvenain, thanks
